### ISSUE TITLE
CrossArc crashes when trying to extract mario_odyssey_sunny_cube_spc.nutexb from data.arc v1.0.0

### ISSUE THREAD

**Issue by Yoshimaster96** [Ploaj/ArcCross#12]
One of the first files in the archive, `mario_odyssey_sunny_cube_spc.nutexb`, causes the program to crash for some reason. (I'm extracting the 1.0.0 files).

[EDIT]
Never mind, after setting the language to "American English", it keeps going, but it does still eventually crash at some file. It was going too fast to tell what file it was though.

**Comment by ScanMountGoat** [comment]
Path: `stage/mario_odyssey/normal/model/odysseyship_rigid_set/mario_odyssey_sunny_cube_spc.nutexb`
```
System.IO.IOException: 'Unknown frame descriptor'
   at Zstandard.Net.ZstandardInterop.ThrowIfError(UIntPtr code)
   at Zstandard.Net.ZstandardStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at ArcCross.ExtBinaryReader.DecompressZstd(Byte[] compressed)
   at ArcCross.Arc.GetFile(String filepath, Int32 regionIndex)
   at CrossArc.GUI.ProgressBar.SaveFile(String filepath, String arcpath, Int32 i) in C:\Users\Jonathan\Documents\GITHUB\ArcCross\CrossArc\GUI\ProgressBar.cs:line 122
   at CrossArc.GUI.ProgressBar.ExtractFileInformation() in C:\Users\Jonathan\Documents\GITHUB\ArcCross\CrossArc\GUI\ProgressBar.cs:line 87
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
